# This is a basic workflow to help you get started with Actions

name: DevCard


permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set Up Git Identity
        run: |
          git config --global user.name = "AksharP5"
          git config --global user.email "aksharpatel1233@gmail.com"
          
      - name: devcard
        uses: dailydotdev/action-devcard@3.1.0
        with:
          user_id: ${{ secrets.DEVCARD_ID }}
          commit_message: "chore: update ${filename}" 
